import './globals.css'
import { Inter } from 'next/font/google'
import { Space_Grotesk } from 'next/font/google' 

const space_grotesk = Space_Grotesk({ subsets: ['latin'], weight: ['400', '700'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={space_grotesk.className}>{children}</body>
    </html>
  )
}
